run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Checking for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Checks for unused constants, variables, functions and types
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Checks import order
    - misspell      # Finds commonly misspelled English words
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - revive        # Fast, configurable, extensible, flexible linter
    - gosec         # Inspects source code for security problems
    - unparam       # Reports unused function parameters
    - unconvert     # Remove unnecessary type conversions
    - gocyclo       # Computes and checks cyclomatic complexity
    - gocognit      # Computes and checks cognitive complexity
    - bodyclose     # Checks whether HTTP response body is closed
    - noctx         # Finds sending http request without context.Context
    - nilnil        # Checks that there is no nil returns
    - errname       # Checks error naming conventions
    - errorlint     # Error wrapping
    - contextcheck  # Check the function whether use a non-inherited context

linters-settings:
  gocyclo:
    min-complexity: 15  # Maximum cyclomatic complexity per function
  
  gocognit:
    min-complexity: 20  # Maximum cognitive complexity per function
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
  
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocritic
    
    # Exclude known false positives
    - text: "should have a package comment"
      linters:
        - revive
      path: _test\.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

